### ISSUE TITLE
Extension crashes with flake8 6.0.0 (Python 3.8.10)

### ISSUE THREAD

**Issue by TimStricker** [microsoft/vscode-flake8#184]
# Problem Description

I'm usually using the extension with flake8 (v6.0.0, Python 3.8.10) loaded from my environment. Since 2023.6.0, it started crashing due to this:

```
2023-07-19 15:51:06.405 [info] Server: Start requested.
2023-07-19 15:51:06.744 [info] Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.flake8-2023.6.0/bundled/tool/lsp_server.py", line 40, in <module>
    from pygls import server, uris, workspace
  File "/root/.vscode-server/extensions/ms-python.flake8-2023.6.0/bundled/libs/pygls/server.py", line 27, in <module>
    from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType
  File "/root/.vscode-server/extensions/ms-python.flake8-2023.6.0/bundled/libs/pygls/lsp/__init__.py", line 36, in <module>
    from typeguard import check_type
  File "/root/.vscode-server/extensions/ms-python.flake8-2023.6.0/bundled/libs/typeguard/__init__.py", line 47, in <module>
    load_plugins()
  File "/root/.vscode-server/extensions/ms-python.flake8-2023.6.0/bundled/libs/typeguard/_checkers.py", line 770, in load_plugins
    for ep in entry_points(group="typeguard.checker_lookup"):
TypeError: entry_points() got an unexpected keyword argument 'group'

2023-07-19 15:51:06.792 [info] [Error - 3:51:06 PM] Server initialization failed.
```

Changing to the bundled version fixes the problem. 

# Analysis

I think the problem is that the `group` argument for the `entry_points` function was only added in Python 3.10, so it cannot work with 3.8. I am however a bit confused why it works with the bundled version of flake8 which is still using Python 3.8 from my system I think. But maybe for some reason it's just not calling that function?

This is the commit that introduced the usage of `group` in typeguard (released with v3.0.0): agronholm/typeguard@81df64f75ce679a3e2b28104e9cb4b5a318af336
This is the commit that upgraded the extension to the new typeguard version: 9e415381c73223b729c1be03f15edcd5339c9de3

# Version information: 

VS Code: `1.80.1`
Flake8 Extension:  `2023.6.0`
Bundled flake8: `5.0.4 (mccabe: 0.7.0, pycodestyle: 2.9.1, pyflakes: 2.5.0) CPython 3.8.10 on
Linux`
flake8 from my environment: `6.0.0 (mccabe: 0.7.0, pycodestyle: 2.10.0, pyflakes: 3.0.1) CPython 3.8.10 on Linux`

**Comment by karthiknadig** [comment]
The bundled one is pinned to the version of `flake8` that is supported with python 3.7. It will be bound to that version till end of September since we support End-of-life python for 3 months.

Can you share the exact version of python 3.8 that you are using? and also could you do a `python -m pip list` in your environment so I understand what is going on.

Alternate way to get `flake8` working. Set `flake8.path` to something like `${workspaceFolder}/bin/flake8` and see if that helps with this. Leave the `flake8.importStrategy` to `useBundled`.

**Comment by TimStricker** [comment]
> Can you share the exact version of python 3.8 that you are using? and also could you do a python -m pip list in your environment so I understand what is going on.

Certainly, there you go:

```
# python --version
Python 3.8.10
```

<details><summary><code># python -m pip list</code></summary>

```
# python -m pip list
Package                    Version             
-------------------------- --------------------
actionlib                  1.14.0              
angles                     1.9.13              
bcrypt                     3.1.7               
black                      23.3.0              
bondpy                     1.8.6               
camera-calibration-parsers 1.12.0              
catkin                     0.8.10              
catkin-pkg                 0.5.2               
catkin-pkg-modules         0.5.2               
catkin-tools               0.9.2               
certifi                    2019.11.28          
chardet                    3.0.4               
click                      8.1.3               
cryptography               2.8                 
cv-bridge                  1.16.2              
dbus-python                1.2.16              
defusedxml                 0.6.0               
diagnostic-updater         1.11.0              
distro                     1.4.0               
distro-info                0.23ubuntu1         
docutils                   0.16                
dynamic-reconfigure        1.7.3               
empy                       3.3.2               
exceptiongroup             1.1.1               
flake8                     6.0.0               
gencpp                     0.7.0               
geneus                     3.0.0               
genlisp                    0.4.18              
genmsg                     0.6.0               
gennodejs                  2.0.2               
genpy                      0.6.15              
greenlet                   0.4.15              
idna                       2.8                 
image-geometry             1.16.2              
importlib-metadata         1.5.0               
iniconfig                  2.0.0               
interactive-markers        1.12.0              
isort                      5.12.0              
Jetson.GPIO                2.1.1               
laser-geometry             1.6.7               
mccabe                     0.7.0               
message-filters            1.16.0              
mock                       5.0.2               
more-itertools             4.2.0               
msgpack                    0.6.2               
mypy-extensions            1.0.0               
netifaces                  0.10.4              
nmea-navsat-driver         0.6.1               
nose                       1.3.7               
numpy                      1.17.4              
osrf-pycommon              2.0.2               
packaging                  23.1                
paramiko                   2.6.0               
pathspec                   0.11.1              
pip                        20.0.2              
platformdirs               3.8.0               
pluggy                     1.2.0               
protobuf                   3.17.3              
pycodestyle                2.10.0              
pycryptodomex              3.6.1               
pyflakes                   3.0.1               
Pygments                   2.3.1               
PyGObject                  3.36.0              
PyNaCl                     1.3.0               
pynvim                     0.4.1               
pyparsing                  2.4.6               
PyQt5                      5.14.1              
pyserial                   3.4                 
pytest                     7.4.0               
python-apt                 2.0.1+ubuntu0.20.4.1
python-dateutil            2.7.3               
python-gnupg               0.4.5               
python-qt-binding          0.4.4               
PyYAML                     5.3.1               
qt-gui                     0.4.2               
qt-gui-cpp                 0.4.2               
requests                   2.22.0              
requests-unixsocket        0.2.0               
resource-retriever         1.12.7              
roman                      2.0.0               
rosbag                     1.16.0              
rosboost-cfg               1.15.8              
rosclean                   1.15.8              
roscreate                  1.15.8              
rosdep                     0.22.2              
rosdep-modules             0.22.2              
rosdistro                  0.9.0               
rosdistro-modules          0.9.0               
rosgraph                   1.16.0              
rosinstall                 0.7.8               
roslaunch                  1.16.0              
roslib                     1.15.8              
roslz4                     1.16.0              
rosmake                    1.15.8              
rosmaster                  1.16.0              
rosmsg                     1.16.0              
rosnode                    1.16.0              
rosparam                   1.16.0              
rospkg                     1.5.0               
rospkg-modules             1.5.0               
rospy                      1.16.0              
rosservice                 1.16.0              
rostest                    1.16.0              
rostopic                   1.16.0              
rosunit                    1.15.8              
roswtf                     1.16.0              
rqt-gui                    0.5.3               
rviz                       1.14.20             
sensor-msgs                1.13.1              
setuptools                 45.2.0              
sip                        4.19.21             
six                        1.14.0              
smclib                     1.8.6               
tf                         1.13.2              
tf-conversions             1.13.2              
tf2-geometry-msgs          0.7.6               
tf2-py                     0.7.6               
tf2-ros                    0.7.6               
tomli                      2.0.1               
topic-tools                1.16.0              
typing-extensions          4.6.3               
unattended-upgrades        0.1                 
urllib3                    1.25.8              
vcstools                   0.1.42              
wheel                      0.34.2              
wstool                     0.1.18              
zipp                       1.0.0 
```
</details>

> Alternate way to get flake8 working. Set flake8.path to something like ${workspaceFolder}/bin/flake8 and see if that helps with this. Leave the flake8.importStrategy to useBundled.

Setting the path doesn't make a difference. Sure, I can just use the bundled version for now. But I guess it's still a bug that it isn't working with the version from the environment when all stated requirements are met (python >= 3.7, flake8 >= 5.0.0) .

**Comment by karthiknadig** [comment]
We ship https://pypi.org/project/typeguard/3.0.2/ typeguard version v3.0.2 which is marked to support python >= 3.7.4.

The issue is due to `importlib-metadata`, the one that we ship with is different from the one in your environment, so it seems like `entry_point` is being pulled form, see in typeguard:
https://github.com/agronholm/typeguard/blob/db7771024eb2f6eba03c3954f8abe0f03bded3c2/src/typeguard/_checkers.py#L70-L75
